### PR TITLE
Fixes incorrect name reflection issue for NServiceBus 7.2

### PR DESCRIPTION
**Pull request by dvdstelt**
Solves https://github.com/NServiceBusExtensions/NServiceBus.HandlerOrdering/issues/79

### CODE REVIEW

**Comment by dvdstelt** [comment]
Didn't check anything, just fixed the name it was searching for.

**Comment by SimonCropp** [comment]
how about instead of keeping the fragile code in this repo. scanned types can be made a public api in NServiceBus?

**Comment by SimonCropp** [comment]
@dvdstelt any progress on making this a public API in NSB?

**Comment by dvdstelt** [comment]
Unlikely to happen soon.

**Comment by SimonCropp** [comment]
@dvdstelt no worries. let me know when that is done and we can revisit this

**Comment by SimonCropp** [comment]
closing this one for now. ping me when the new API is added to NSB

**Pull request closed without merging**
